bot:
  type: union
  name: Jet Bot
  description: The Telegram Bot for Lightning Jet
  tag:
    id: enable
    name: Enable
    description: |
      - Enabled: The Telegram Bot will communicate with Lightning Jet on your Embassy.
      - Disabled: The Telegram Bot will be disabled.
    variant-names:
      disable: Disabled
      enable: Enabled
  default: disable
  variants:
    disable: {}
    enable:
      token:
        type: string
        name: Telegram API Token
        description: Telegram Token from the Telegram app chat with BotFather
        nullable: false